import test from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../server.mjs';

test('Account isolation, device commands, expiry, schedules and revocation',async t=>{
  let clock=Date.parse('2026-10-04T00:00:00Z');
  const app=createApp({dbPath:':memory:',now:()=>clock});
  await new Promise(r=>app.server.listen(0,'app.sunifactory.com',r));
  t.after(async()=>{await new Promise(r=>app.server.close(r));app.close();});
  const base=`https://app.sunifactory.com/`;
  const configs=new Map();
  async function req(p,{method='GET',body,cookie,token,headers={}}={}){
    if(p==='/device/poll'&&body===undefined)body={protocol:4,applied_config:configs.get(token)};
    const r=await fetch(base+'/api'+p,{method,headers:{'Content-Type':'application/json','X-Requested-With':'PawMeal',...(cookie?{Cookie:cookie}:{}),...(token?{Authorization:'Bearer '+token}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
    const data=await r.json();if(p==='/device/poll'&&data.config)configs.set(token,data.config);
    return {status:r.status,body:data,cookie:r.headers.get('set-cookie')?.split(';')[0]};
  }
  const a=await req('/register',{method:'POST',body:{email:'a@example.com',password:'long-password-1'}});
  const b=await req('/register',{method:'POST',body:{email:'b@example.com',password:'long-password-2'}});
  assert.equal(a.status,200);assert.equal(b.status,200);
  let cookie=a.cookie;
  assert.equal((await req('/state')).status,401);
  assert.equal((await req('/login',{method:'POST',body:{email:'a@example.com',password:'wrong-password'}})).status,401);
  assert.equal((await req('/login',{method:'POST',body:{email:'a@example.com',password:'long-password-1'}})).status,200);
  assert.equal((await req('/devices',{method:'POST',cookie,body:{name:'bad'},headers:{Origin:'https://evil.example'}})).status,403);
  const added=await req('/devices',{method:'POST',cookie,body:{name:'Miu'}});
  const {id,token}=added.body, p=`/devices/${id}`;
  assert.equal(added.status,201);assert.equal(token.length,64);
  const added2=await req('/devices',{method:'POST',cookie,body:{name:'Cún'}});
  assert.equal((await req('/state',{cookie})).body.devices.length,2);
  assert.equal((await req('/state',{cookie:b.cookie})).body.devices.length,0);
  assert.equal((await req(p,{method:'DELETE',cookie:b.cookie})).status,404);
  assert.equal((await req(p+'/feed',{method:'POST',cookie})).status,409);
  assert.equal((await req('/device/poll',{method:'POST',token:'wrong'})).status,401);
  await req('/device/poll',{method:'POST',token});
  await req('/device/poll',{method:'POST',token});
  assert.equal((await req(p,{method:'PATCH',cookie,body:{name:'Miu',portions:1,portion_ms:11000,closed_angle:60,open_angle:90,move_ms:700}})).status,400);
  assert.equal((await req(p,{method:'PATCH',cookie,body:{name:'Miu',portions:1,portion_ms:500,closed_angle:60,open_angle:90,move_ms:700}})).status,200);
  await req('/device/poll',{method:'POST',token});
  await req('/device/poll',{method:'POST',token});
  const feed=await req(p+'/feed',{method:'POST',cookie});assert.equal(feed.status,201);
  assert.equal((await req(p+'/feed',{method:'POST',cookie})).status,409);
  const poll=await req('/device/poll',{method:'POST',token});assert.equal(poll.body.command.id,feed.body.id);assert.equal(poll.body.command.run_ms,500);
  assert.equal((await req('/device/poll',{method:'POST',token})).body.command,null,'no redelivery');
  await req('/device/ack',{method:'POST',token:added2.body.token,body:{id:feed.body.id,status:'completed'}});
  assert.equal((await req('/state',{cookie})).body.events[0].status,'delivered','other device cannot ACK');
  await req('/device/ack',{method:'POST',token,body:{id:feed.body.id,status:'completed'}});
  await req('/device/ack',{method:'POST',token,body:{id:feed.body.id,status:'interrupted'}});
  assert.equal((await req('/state',{cookie})).body.events[0].status,'completed','ACK is idempotent');
  clock+=11000;
  await req(p+'/feed',{method:'POST',cookie});clock+=16000;
  assert.equal((await req('/device/poll',{method:'POST',token})).body.command,null,'stale command expires');
  assert.equal((await req('/state',{cookie})).body.events[0].status,'expired');
  assert.equal((await req(p+'/schedules',{method:'POST',cookie,body:{time:'07:01',days:[0]}})).status,201);
  assert.equal((await req(p+'/schedules',{method:'POST',cookie,body:{time:'07:01',days:[0]}})).status,409);
  assert.equal((await req(p+'/schedules',{method:'POST',cookie,body:{time:'24:99',days:[0]}})).status,400);
  clock=Date.parse('2026-10-04T00:01:00Z');await req('/device/poll',{method:'POST',token});app.tick();app.tick();
  let events=(await req('/state',{cookie})).body.events;
  assert.equal(events.filter(e=>e.source==='schedule').length,1,'one schedule per Vietnam day');
  assert.equal(events[0].status,'queued');
  const scheduled=await req('/device/poll',{method:'POST',token});
  clock+=80000;app.tick();assert.equal((await req('/state',{cookie})).body.events[0].status,'unknown');
  await req('/device/ack',{method:'POST',token,body:{id:scheduled.body.command.id,status:'interrupted'}});
  assert.equal((await req('/state',{cookie})).body.events[0].status,'interrupted');
  clock=Date.parse('2026-10-11T00:01:00Z');app.tick();
  cookie=(await req('/login',{method:'POST',body:{email:'a@example.com',password:'long-password-1'}})).cookie;
  assert.equal((await req('/state',{cookie})).body.events[0].status,'skipped','offline schedule skipped');
  await req('/device/poll',{method:'POST',token});app.tick();
  assert.equal((await req('/device/poll',{method:'POST',token})).body.command,null,'offline schedule does not catch up');
  const rotated=await req(p+'/token',{method:'POST',cookie});
  assert.equal((await req('/device/poll',{method:'POST',token})).status,401);
  assert.equal((await req('/device/poll',{method:'POST',token:rotated.body.token})).status,200);
  assert.equal((await req(p,{method:'DELETE',cookie})).status,200);
  assert.equal((await req('/device/poll',{method:'POST',token:rotated.body.token})).status,401);
  assert.equal((await req('/state',{cookie})).body.events.length,0);
  await req('/logout',{method:'POST',cookie});assert.equal((await req('/state',{cookie})).status,401);
});
